version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: "yara_db"
    ports:
      - 27017:27017

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code


